"""Small TRACKED reference resources -- verified source data, never generated output.

Kept as version-controlled package resources (never scraped at runtime,
never regenerated by a pipeline stage) so a verified transcription of an
official source document is reproducible and auditable exactly like code.
"""

from pathlib import Path
from typing import Any

import pandas as pd

RESOURCES_DIR = Path(__file__).parent

ANGLIA_TABLE_B1_FREESPANS_CSV = RESOURCES_DIR / "anglia_table_b1_freespans.csv"

ANGLIA_TABLE_B1_COLUMNS = (
    "survey_year",
    "event_id",
    "source_survey_kp_start_km",
    "source_survey_kp_end_km",
    "source_easting_start_m",
    "source_northing_start_m",
    "source_easting_end_m",
    "source_northing_end_m",
    "source_length_m",
    "source_height_m",
    "source_comment",
    "asset_scope",
    "evidence_role",
    "source_page",
    "source_table",
)

# Verified checksums (MAR-014A Sections 4-6) -- the source's own rounded
# summary statements, reproduced here so a transcription error is caught
# immediately rather than silently propagating downstream.
_EXPECTED_CHECKSUMS: dict[int, dict[str, Any]] = {
    2012: {"count": 2, "sum_length_m": 23.20},
    2014: {"count": 7, "sum_length_m": 68.23},
    2018: {"count": 8, "sum_length_m": 97.42, "max_length_m": 23.16, "max_height_m": 0.41},
}

_CHECKSUM_TOLERANCE_M = 0.005  # transcription-exactness tolerance, not a physical tolerance


class AngliaTableB1ChecksumError(Exception):
    """The tracked resource does not reproduce the source's own verified checksums."""


def load_anglia_table_b1_freespans() -> pd.DataFrame:
    """The verified Table B.1 freespan rows (2012/2014/2018), as tracked source data.

    Hard-fails (`AngliaTableB1ChecksumError`) if the on-disk resource does
    not reproduce the source document's own rounded per-year summary
    statements -- a transcription/edit error must never silently
    propagate into canonical outputs.
    """

    df = pd.read_csv(ANGLIA_TABLE_B1_FREESPANS_CSV)
    missing_columns = [c for c in ANGLIA_TABLE_B1_COLUMNS if c not in df.columns]
    if missing_columns:
        raise AngliaTableB1ChecksumError(
            f"anglia_table_b1_freespans.csv is missing required column(s): {missing_columns}"
        )

    for year, expected in _EXPECTED_CHECKSUMS.items():
        year_rows = df[df["survey_year"] == year]
        actual_count = int(len(year_rows))
        actual_sum = float(year_rows["source_length_m"].sum())

        if actual_count != expected["count"]:
            raise AngliaTableB1ChecksumError(
                f"{year} event count is {actual_count}, expected {expected['count']}"
            )
        if abs(actual_sum - expected["sum_length_m"]) > _CHECKSUM_TOLERANCE_M:
            raise AngliaTableB1ChecksumError(
                f"{year} sum(source_length_m) is {actual_sum:.2f} m, expected "
                f"{expected['sum_length_m']:.2f} m"
            )
        if "max_length_m" in expected:
            actual_max_length = float(year_rows["source_length_m"].max())
            if abs(actual_max_length - expected["max_length_m"]) > _CHECKSUM_TOLERANCE_M:
                raise AngliaTableB1ChecksumError(
                    f"{year} max(source_length_m) is {actual_max_length:.2f} m, expected "
                    f"{expected['max_length_m']:.2f} m"
                )
        if "max_height_m" in expected:
            actual_max_height = float(year_rows["source_height_m"].max())
            if abs(actual_max_height - expected["max_height_m"]) > _CHECKSUM_TOLERANCE_M:
                raise AngliaTableB1ChecksumError(
                    f"{year} max(source_height_m) is {actual_max_height:.2f} m, expected "
                    f"{expected['max_height_m']:.2f} m"
                )

    return df[list(ANGLIA_TABLE_B1_COLUMNS)]
